version: '3'

services:
  minerva-api:
    image: postgres:alpine
    ports:
      - '5430:5432'
    container_name: 'grain-database'
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=grain-api

volumes:
  database: